
// Gossip Menus and more
enum GossipId
{
    // ###################
    // Mechanical Chicken
    // ###################
    WOS_MC_GOSSIP_TEXT = 1041,
    WOS_MC_GOSSIP_TAKE_ME_TO_STORMWIND = 2100,
    WOS_MC_GOSSIP_TAKE_ME_TO_IRONFORGE = 2101,
    WOS_MC_GOSSIP_TAKE_ME_TO_DARNASSUS = 2102,
    WOS_MC_GOSSIP_TAKE_ME_TO_EXODAR = 2103,
    WOS_MC_GOSSIP_TAKE_ME_TO_ORGRIMMAR = 2104,
    WOS_MC_GOSSIP_TAKE_ME_TO_THUNDERBLUFF = 2105,
    WOS_MC_GOSSIP_TAKE_ME_TO_UNDERCITY = 2106,
    WOS_MC_GOSSIP_TAKE_ME_TO_SILVERMOONCITY = 2107,
    WOS_MC_GOSSIP_TAKE_ME_TO_SHATTRATH = 2108,
    WOS_MC_GOSSIP_TAKE_ME_TO_DALARAN_ALLIANCE = 2109,
    WOS_MC_GOSSIP_TAKE_ME_TO_DALARAN_HORDE = 2110,
    WOS_MC_GOSSIP_TAKE_ME_TO_STAGE_ONE = 2111,
    WOS_MC_GOSSIP_TAKE_ME_TO_STAGE_TWO = 2112,
    WOS_MC_GOSSIP_TAKE_ME_TO_STAGE_THREE = 2113,
};
