
// Gossip Menus and more
enum GossipId
{
    // ####################
    // Minigob Manabonk
    // ####################

    // The basic "Greetings, $n"
    WOS_MM_GOSSIP_TEXT = 68,
    WOS_MC_GOSSIP_GREETING = 4000000,
    WOS_MC_GOSSIP_GREETING_NO_OIL = 4000001,


    // The Emblem of Honor gossip menus
    // Top level menu:
    WOS_MM_GOSSIP_VALOR = 1000,

    // Custom greetings/text
    WOS_MM_GOSSIP_CHITCHAT_DALARAN_TELEPORT = 3000000,
    WOS_MM_GOSSIP_CHITCHAT_FLIGHT_PATHS = 3000001,
    WOS_MM_GOSSIP_CHITCHAT_LEVEL = 3000002,
    WOS_MM_GOSSIP_CHITCHAT_MECHANICAL_CHICKEN = 3000003,
    WOS_MM_GOSSIP_CHITCHAT_MOUNT = 3000004,


    // I want to boost my level as the grind it too much
    WOS_MM_GOSSIP_VALOR_LEVEL = 1100,
    WOS_MM_GOSSIP_VALOR_LEVEL_ONE = 1101,
    WOS_MM_GOSSIP_VALOR_LEVEL_TWO = 1102,
    WOS_MM_GOSSIP_VALOR_LEVEL_THREE = 1103,
    WOS_MM_GOSSIP_VALOR_LEVEL_FIVE = 1104,

    // I want to learn about flight master locations
    WOS_MM_GOSSIP_VALOR_FLIGHT_PATHS = 1200,
    WOS_MM_GOSSIP_VALOR_FLIGHT_PATHS_CONFIRM = 1201,

    // I need a quick get away to Dalaran, stat!
    WOS_MM_GOSSIP_VALOR_DALARAN_TELEPORT = 1300,
    WOS_MM_GOSSIP_VALOR_DALARAN_TELEPORT_CONFIRM = 1301,
    WOS_MM_GOSSIP_VALOR_DALARAN_TELEPORT_BEG = 1302,

    WOS_MM_GOSSIP_VALOR_MECHANICAL_CHICKEN = 1400,
    WOS_MM_GOSSIP_VALOR_MECHANICAL_CHICKEN_BUY = 1401,
    WOS_MM_GOSSIP_VALOR_MECHANICAL_CHICKEN_OIL_BUY = 1402,

    // I want to buy a mount
    WOS_MM_GOSSIP_VALOR_BUY_MOUNT = 1500,
    WOS_MM_GOSSIP_VALOR_BUY_MOUNT_BUY = 1501,

    // ###################
    // Mechanical Chicken
    // ###################

    WOS_MC_GOSSIP_TEXT = 1041,
    WOS_MC_GOSSIP_TAKE_ME_TO_STORMWIND = 2100,
    WOS_MC_GOSSIP_TAKE_ME_TO_IRONFORGE = 2101,
    WOS_MC_GOSSIP_TAKE_ME_TO_DARNASSUS = 2102,
    WOS_MC_GOSSIP_TAKE_ME_TO_EXODAR = 2103,
    WOS_MC_GOSSIP_TAKE_ME_TO_ORGRIMMAR = 2104,
    WOS_MC_GOSSIP_TAKE_ME_TO_THUNDERBLUFF = 2105,
    WOS_MC_GOSSIP_TAKE_ME_TO_UNDERCITY = 2106,
    WOS_MC_GOSSIP_TAKE_ME_TO_SILVERMOONCITY = 2107,
    WOS_MC_GOSSIP_TAKE_ME_TO_SHATTRATH = 2108,
    WOS_MC_GOSSIP_TAKE_ME_TO_DALARAN_ALLIANCE = 2109,
    WOS_MC_GOSSIP_TAKE_ME_TO_DALARAN_HORDE = 2110,

};
